/*
 imagesLoaded PACKAGED v4.1.4
 JavaScript is all like "You images are done yet or what?"
 MIT License
 imagesLoaded v4.1.4
 JavaScript is all like "You images are done yet or what?"
 MIT License
*/
!function(g,f){"function"==typeof define&&define.amd?define("ev-emitter/ev-emitter",f):"object"==typeof module&&module.exports?module.exports=f():g.EvEmitter=f()}("undefined"!=typeof window?window:this,function(){function g(){}var f=g.prototype;return f.on=function(d,b){if(d&&b){var c=this._events=this._events||{};d=c[d]=c[d]||[];return-1==d.indexOf(b)&&d.push(b),this}},f.once=function(d,b){if(d&&b){this.on(d,b);var c=this._onceEvents=this._onceEvents||{};return(c[d]=c[d]||{})[b]=!0,this}},f.off=
function(d,b){if((d=this._events&&this._events[d])&&d.length)return b=d.indexOf(b),-1!=b&&d.splice(b,1),this},f.emitEvent=function(d,b){var c=this._events&&this._events[d];if(c&&c.length){c=c.slice(0);b=b||[];for(var f=this._onceEvents&&this._onceEvents[d],g=0;g<c.length;g++){var h=c[g];f&&f[h]&&(this.off(d,h),delete f[h]);h.apply(this,b)}return this}},f.allOff=function(){delete this._events;delete this._onceEvents},g});
(function(g,f){"function"==typeof define&&define.amd?define(["ev-emitter/ev-emitter"],function(d){return f(g,d)}):"object"==typeof module&&module.exports?module.exports=f(g,require("ev-emitter")):g.imagesLoaded=f(g,g.EvEmitter)})("undefined"!=typeof window?window:this,function(g,f){function d(a,e){for(var b in e)a[b]=e[b];return a}function b(a,e,c){if(!(this instanceof b))return new b(a,e,c);var f=a;"string"==typeof a&&(f=document.querySelectorAll(a));f?(a=f,this.elements=Array.isArray(a)?a:"object"==
typeof a&&"number"==typeof a.length?m.call(a):[a],this.options=d({},this.options),"function"==typeof e?c=e:d(this.options,e),c&&this.on("always",c),this.getImages(),l&&(this.jqDeferred=new l.Deferred),setTimeout(this.check.bind(this))):h.error("Bad element for imagesLoaded "+(f||a))}function c(a){this.img=a}function k(a,e){this.url=a;this.element=e;this.img=new Image}var l=g.jQuery,h=g.console,m=Array.prototype.slice;b.prototype=Object.create(f.prototype);b.prototype.options={};b.prototype.getImages=
function(){this.images=[];this.elements.forEach(this.addElementImages,this)};b.prototype.addElementImages=function(a){"IMG"==a.nodeName&&this.addImage(a);!0===this.options.background&&this.addElementBackgroundImages(a);var e=a.nodeType;if(e&&n[e]){var b=a.querySelectorAll("img");for(e=0;e<b.length;e++)this.addImage(b[e]);if("string"==typeof this.options.background)for(a=a.querySelectorAll(this.options.background),e=0;e<a.length;e++)this.addElementBackgroundImages(a[e])}};var n={1:!0,9:!0,11:!0};return b.prototype.addElementBackgroundImages=
function(a){var e=getComputedStyle(a);if(e)for(var b=/url\((['"])?(.*?)\1\)/gi,c=b.exec(e.backgroundImage);null!==c;)(c=c&&c[2])&&this.addBackground(c,a),c=b.exec(e.backgroundImage)},b.prototype.addImage=function(a){a=new c(a);this.images.push(a)},b.prototype.addBackground=function(a,b){a=new k(a,b);this.images.push(a)},b.prototype.check=function(){function a(a,e,c){setTimeout(function(){b.progress(a,e,c)})}var b=this;this.progressedCount=0;this.hasAnyBroken=!1;this.images.length?this.images.forEach(function(b){b.once("progress",
a);b.check()}):this.complete()},b.prototype.progress=function(a,b,c){this.progressedCount++;this.hasAnyBroken=this.hasAnyBroken||!a.isLoaded;this.emitEvent("progress",[this,a,b]);this.jqDeferred&&this.jqDeferred.notify&&this.jqDeferred.notify(this,a);this.progressedCount==this.images.length&&this.complete();this.options.debug&&h&&h.log("progress: "+c,a,b)},b.prototype.complete=function(){var a=this.hasAnyBroken?"fail":"done";if(this.isComplete=!0,this.emitEvent(a,[this]),this.emitEvent("always",[this]),
this.jqDeferred)this.jqDeferred[this.hasAnyBroken?"reject":"resolve"](this)},c.prototype=Object.create(f.prototype),c.prototype.check=function(){this.getIsImageComplete()?this.confirm(0!==this.img.naturalWidth,"naturalWidth"):(this.proxyImage=new Image,this.proxyImage.addEventListener("load",this),this.proxyImage.addEventListener("error",this),this.img.addEventListener("load",this),this.img.addEventListener("error",this),this.proxyImage.src=this.img.src)},c.prototype.getIsImageComplete=function(){return this.img.complete&&
this.img.naturalWidth},c.prototype.confirm=function(a,b){this.isLoaded=a;this.emitEvent("progress",[this,this.img,b])},c.prototype.handleEvent=function(a){var b="on"+a.type;this[b]&&this[b](a)},c.prototype.onload=function(){this.confirm(!0,"onload");this.unbindEvents()},c.prototype.onerror=function(){this.confirm(!1,"onerror");this.unbindEvents()},c.prototype.unbindEvents=function(){this.proxyImage.removeEventListener("load",this);this.proxyImage.removeEventListener("error",this);this.img.removeEventListener("load",
this);this.img.removeEventListener("error",this)},k.prototype=Object.create(c.prototype),k.prototype.check=function(){this.img.addEventListener("load",this);this.img.addEventListener("error",this);this.img.src=this.url;this.getIsImageComplete()&&(this.confirm(0!==this.img.naturalWidth,"naturalWidth"),this.unbindEvents())},k.prototype.unbindEvents=function(){this.img.removeEventListener("load",this);this.img.removeEventListener("error",this)},k.prototype.confirm=function(a,b){this.isLoaded=a;this.emitEvent("progress",
[this,this.element,b])},b.makeJQueryPlugin=function(a){(a=a||g.jQuery)&&((l=a).fn.imagesLoaded=function(a,c){return(new b(this,a,c)).jqDeferred.promise(l(this))})},b.makeJQueryPlugin(),b});