/*
 Name    : Video Background Extension for Jarallax
 Version : 1.0.1
 Author  : nK <https://nkdev.info>
 GitHub  : https://github.com/nk-o/jarallax
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,e){a!=Array.prototype&&a!=Object.prototype&&(a[c]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var e=0,d={next:function(){if(e<a.length){var h=e++;return{value:c(h,a[h]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,c,e,d){if(c){e=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var h=a[d];h in e||(e[h]={});e=e[h]}a=a[a.length-1];d=e[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
!function(a){function c(d){if(e[d])return e[d].exports;var h=e[d]={i:d,l:!1,exports:{}};return a[d].call(h.exports,h,h.exports,c),h.l=!0,h.exports}var e={};c.m=a;c.c=e;c.d=function(d,a,e){c.o(d,a)||Object.defineProperty(d,a,{enumerable:!0,get:e})};c.r=function(d){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(d,Symbol.toStringTag,{value:"Module"});Object.defineProperty(d,"__esModule",{value:!0})};c.t=function(d,a){if((1&a&&(d=c(d)),8&a)||4&a&&"object"==typeof d&&d&&d.__esModule)return d;
var e=Object.create(null);if(c.r(e),Object.defineProperty(e,"default",{enumerable:!0,value:d}),2&a&&"string"!=typeof d)for(var h in d)c.d(e,h,function(a){return d[a]}.bind(null,h));return e};c.n=function(a){var d=a&&a.__esModule?function(){return a.default}:function(){return a};return c.d(d,"a",d),d};c.o=function(a,c){return Object.prototype.hasOwnProperty.call(a,c)};c.p="";c(c.s=6)}([,,function(a,c,e){a.exports=function(a){"complete"===document.readyState||"interactive"===document.readyState?a.call():
document.attachEvent?document.attachEvent("onreadystatechange",function(){"interactive"===document.readyState&&a.call()}):document.addEventListener&&document.addEventListener("DOMContentLoaded",a)}},,function(a,c,e){c=e(5);a.exports="undefined"!=typeof window?window:void 0!==c?c:"undefined"!=typeof self?self:{}},function(a,c,e){e="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?
"symbol":typeof a};c=function(){return this}();try{c=c||Function("return this")()||(0,eval)("this")}catch(d){"object"===("undefined"==typeof window?"undefined":e(window))&&(c=window)}a.exports=c},function(a,c,e){a.exports=e(7)},function(a,c,e){function d(a){return a&&a.__esModule?a:{default:a}}a=d(e(8));c=d(e(4));var h=d(e(2));e=d(e(10));c.default.VideoWorker=c.default.VideoWorker||a.default;(0,e.default)();(0,h.default)(function(){"undefined"!=typeof jarallax&&jarallax(document.querySelectorAll("[data-jarallax-video]"))})},
function(a,c,e){a.exports=e(9)},function(a,c,e){function d(){this._done=[];this._fail=[]}Object.defineProperty(c,"__esModule",{value:!0});var h="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},n=function(){function a(f,b){for(var a=0;a<b.length;a++){var g=b[a];g.enumerable=g.enumerable||!1;g.configurable=!0;"value"in g&&(g.writable=!0);Object.defineProperty(f,
g.key,g)}}return function(f,b,g){return b&&a(f.prototype,b),g&&a(f,g),f}}();d.prototype={execute:function(a,f){var b=a.length;for(f=Array.prototype.slice.call(f);b--;)a[b].apply(null,f)},resolve:function(){this.execute(this._done,arguments)},reject:function(){this.execute(this._fail,arguments)},done:function(a){this._done.push(a)},fail:function(a){this._fail.push(a)}};var k=0,p=0,q=0,t=0,l=0,m=new d,g=new d;a=function(){function a(f,b){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");
this.url=f;this.options_default={autoplay:!1,loop:!1,mute:!1,volume:100,showContols:!0,startTime:0,endTime:0};this.options=this.extend({},this.options_default,b);(this.videoID=this.parseURL(f))&&(this.ID=k++,this.loadAPI(),this.init())}return n(a,[{key:"extend",value:function(a){var b=arguments;return a=a||{},Object.keys(arguments).forEach(function(f){b[f]&&Object.keys(b[f]).forEach(function(g){a[g]=b[f][g]})}),a}},{key:"parseURL",value:function(a){var b=function(b){b=b.match(/.*(?:youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=)([^#&\?]*).*/);
return!(!b||11!==b[1].length)&&b[1]}(a),f=function(b){b=b.match(/https?:\/\/(?:www\.|player\.)?vimeo.com\/(?:channels\/(?:\w+\/)?|groups\/([^\/]*)\/videos\/|album\/(\d+)\/video\/|video\/|)(\d+)(?:$|\/|\?)/);return!(!b||!b[3])&&b[3]}(a);a=function(b){var a={},f=0;return b.split(/,(?=mp4:|webm:|ogv:|ogg:)/).forEach(function(b){(b=b.match(/^(mp4|webm|ogv|ogg):(.*)/))&&b[1]&&b[2]&&(a["ogv"===b[1]?"ogg":b[1]]=b[2],f=1)}),!!f&&a}(a);return b?(this.type="youtube",b):f?(this.type="vimeo",f):!!a&&(this.type=
"local",a)}},{key:"isValid",value:function(){return!!this.videoID}},{key:"on",value:function(a,b){this.userEventsList=this.userEventsList||[];(this.userEventsList[a]||(this.userEventsList[a]=[])).push(b)}},{key:"off",value:function(a,b){var f=this;this.userEventsList&&this.userEventsList[a]&&(b?this.userEventsList[a].forEach(function(g,c){g===b&&(f.userEventsList[a][c]=!1)}):delete this.userEventsList[a])}},{key:"fire",value:function(a){var b=this,f=[].slice.call(arguments,1);this.userEventsList&&
void 0!==this.userEventsList[a]&&this.userEventsList[a].forEach(function(a){a&&a.apply(b,f)})}},{key:"play",value:function(a){var b=this;b.player&&("youtube"===b.type&&b.player.playVideo&&(void 0!==a&&b.player.seekTo(a||0),YT.PlayerState.PLAYING!==b.player.getPlayerState()&&b.player.playVideo()),"vimeo"===b.type&&(void 0!==a&&b.player.setCurrentTime(a),b.player.getPaused().then(function(a){a&&b.player.play()})),"local"===b.type&&(void 0!==a&&(b.player.currentTime=a),b.player.paused&&b.player.play()))}},
{key:"pause",value:function(){var a=this;a.player&&("youtube"===a.type&&a.player.pauseVideo&&YT.PlayerState.PLAYING===a.player.getPlayerState()&&a.player.pauseVideo(),"vimeo"===a.type&&a.player.getPaused().then(function(b){b||a.player.pause()}),"local"===a.type&&(a.player.paused||a.player.pause()))}},{key:"mute",value:function(){this.player&&("youtube"===this.type&&this.player.mute&&this.player.mute(),"vimeo"===this.type&&this.player.setVolume&&this.player.setVolume(0),"local"===this.type&&(this.$video.muted=
!0))}},{key:"unmute",value:function(){this.player&&("youtube"===this.type&&this.player.mute&&this.player.unMute(),"vimeo"===this.type&&this.player.setVolume&&this.player.setVolume(this.options.volume),"local"===this.type&&(this.$video.muted=!1))}},{key:"setVolume",value:function(){var a=0<arguments.length&&void 0!==arguments[0]&&arguments[0];this.player&&a&&("youtube"===this.type&&this.player.setVolume&&this.player.setVolume(a),"vimeo"===this.type&&this.player.setVolume&&this.player.setVolume(a),
"local"===this.type&&(this.$video.volume=a/100))}},{key:"getVolume",value:function(a){this.player?("youtube"===this.type&&this.player.getVolume&&a(this.player.getVolume()),"vimeo"===this.type&&this.player.getVolume&&this.player.getVolume().then(function(b){a(b)}),"local"===this.type&&a(100*this.$video.volume)):a(!1)}},{key:"getMuted",value:function(a){this.player?("youtube"===this.type&&this.player.isMuted&&a(this.player.isMuted()),"vimeo"===this.type&&this.player.getVolume&&this.player.getVolume().then(function(b){a(!!b)}),
"local"===this.type&&a(this.$video.muted)):a(null)}},{key:"getImageURL",value:function(a){var b=this;if(b.videoImage)a(b.videoImage);else{if("youtube"===b.type){var g=["maxresdefault","sddefault","hqdefault","0"],f=0,c=new Image;c.onload=function(){120!==(this.naturalWidth||this.width)||f===g.length-1?(b.videoImage="https://img.youtube.com/vi/"+b.videoID+"/"+g[f]+".jpg",a(b.videoImage)):(f++,this.src="https://img.youtube.com/vi/"+b.videoID+"/"+g[f]+".jpg")};c.src="https://img.youtube.com/vi/"+b.videoID+
"/"+g[f]+".jpg"}"vimeo"===b.type&&(c=new XMLHttpRequest,c.open("GET","https://vimeo.com/api/v2/video/"+b.videoID+".json",!0),c.onreadystatechange=function(){if(4===this.readyState&&200<=this.status&&400>this.status){var g=JSON.parse(this.responseText);b.videoImage=g[0].thumbnail_large;a(b.videoImage)}},c.send(),c=null)}}},{key:"getIframe",value:function(a){this.getVideo(a)}},{key:"getVideo",value:function(a){var b=this;b.$video?a(b.$video):b.onAPIready(function(){var g=void 0;if(b.$video||((g=document.createElement("div")).style.display=
"none"),"youtube"===b.type){b.playerOptions={};b.playerOptions.videoId=b.videoID;b.playerOptions.playerVars={autohide:1,rel:0,autoplay:0,playsinline:1};b.options.showContols||(b.playerOptions.playerVars.iv_load_policy=3,b.playerOptions.playerVars.modestbranding=1,b.playerOptions.playerVars.controls=0,b.playerOptions.playerVars.showinfo=0,b.playerOptions.playerVars.disablekb=1);var c=void 0,f=void 0;b.playerOptions.events={onReady:function(a){if(b.options.mute?a.target.mute():b.options.volume&&a.target.setVolume(b.options.volume),
b.options.autoplay&&b.play(b.options.startTime),b.fire("ready",a),b.options.loop&&!b.options.endTime)b.options.endTime=b.player.getDuration()-.1;setInterval(function(){b.getVolume(function(g){b.options.volume!==g&&(b.options.volume=g,b.fire("volumechange",a))})},150)},onStateChange:function(a){b.options.loop&&a.data===YT.PlayerState.ENDED&&b.play(b.options.startTime);c||a.data!==YT.PlayerState.PLAYING||(c=1,b.fire("started",a));a.data===YT.PlayerState.PLAYING&&b.fire("play",a);a.data===YT.PlayerState.PAUSED&&
b.fire("pause",a);a.data===YT.PlayerState.ENDED&&b.fire("ended",a);a.data===YT.PlayerState.PLAYING?f=setInterval(function(){b.fire("timeupdate",a);b.options.endTime&&b.player.getCurrentTime()>=b.options.endTime&&(b.options.loop?b.play(b.options.startTime):b.pause())},150):clearInterval(f)}};var d=!b.$video;if(d){var e=document.createElement("div");e.setAttribute("id",b.playerID);g.appendChild(e);document.body.appendChild(g)}b.player=b.player||new window.YT.Player(b.playerID,b.playerOptions);d&&(b.$video=
document.getElementById(b.playerID),b.videoWidth=parseInt(b.$video.getAttribute("width"),10)||1280,b.videoHeight=parseInt(b.$video.getAttribute("height"),10)||720)}if("vimeo"===b.type){if(b.playerOptions={id:b.videoID,autopause:0,transparent:0,autoplay:b.options.autoplay?1:0,loop:b.options.loop?1:0,muted:b.options.mute?1:0},b.options.volume&&(b.playerOptions.volume=b.options.volume),b.options.showContols||(b.playerOptions.badge=0,b.playerOptions.byline=0,b.playerOptions.portrait=0,b.playerOptions.title=
0),!b.$video){var h="";Object.keys(b.playerOptions).forEach(function(a){""!==h&&(h+="\x26");h+=a+"\x3d"+encodeURIComponent(b.playerOptions[a])});b.$video=document.createElement("iframe");b.$video.setAttribute("id",b.playerID);b.$video.setAttribute("src","https://player.vimeo.com/video/"+b.videoID+"?"+h);b.$video.setAttribute("frameborder","0");b.$video.setAttribute("mozallowfullscreen","");b.$video.setAttribute("allowfullscreen","");g.appendChild(b.$video);document.body.appendChild(g)}b.player=b.player||
new Vimeo.Player(b.$video,b.playerOptions);b.options.startTime&&b.options.autoplay&&b.player.setCurrentTime(b.options.startTime);b.player.getVideoWidth().then(function(a){b.videoWidth=a||1280});b.player.getVideoHeight().then(function(a){b.videoHeight=a||720});var k=void 0;b.player.on("timeupdate",function(a){k||(b.fire("started",a),k=1);b.fire("timeupdate",a);b.options.endTime&&b.options.endTime&&a.seconds>=b.options.endTime&&(b.options.loop?b.play(b.options.startTime):b.pause())});b.player.on("play",
function(a){b.fire("play",a);b.options.startTime&&0===a.seconds&&b.play(b.options.startTime)});b.player.on("pause",function(a){b.fire("pause",a)});b.player.on("ended",function(a){b.fire("ended",a)});b.player.on("loaded",function(a){b.fire("ready",a)});b.player.on("volumechange",function(a){b.fire("volumechange",a)})}if("local"===b.type){b.$video||(b.$video=document.createElement("video"),b.options.showContols&&(b.$video.controls=!0),b.options.mute?b.$video.muted=!0:b.$video.volume&&(b.$video.volume=
b.options.volume/100),b.options.loop&&(b.$video.loop=!0),b.$video.setAttribute("playsinline",""),b.$video.setAttribute("webkit-playsinline",""),b.$video.setAttribute("id",b.playerID),g.appendChild(b.$video),document.body.appendChild(g),Object.keys(b.videoID).forEach(function(a){var g=b.$video,c=b.videoID[a];a="video/"+a;var f=document.createElement("source");f.src=c;f.type=a;g.appendChild(f)}));b.player=b.player||b.$video;var r=void 0;b.player.addEventListener("playing",function(a){r||b.fire("started",
a);r=1});b.player.addEventListener("timeupdate",function(a){b.fire("timeupdate",a);b.options.endTime&&b.options.endTime&&this.currentTime>=b.options.endTime&&(b.options.loop?b.play(b.options.startTime):b.pause())});b.player.addEventListener("play",function(a){b.fire("play",a)});b.player.addEventListener("pause",function(a){b.fire("pause",a)});b.player.addEventListener("ended",function(a){b.fire("ended",a)});b.player.addEventListener("loadedmetadata",function(){b.videoWidth=this.videoWidth||1280;b.videoHeight=
this.videoHeight||720;b.fire("ready");b.options.autoplay&&b.play(b.options.startTime)});b.player.addEventListener("volumechange",function(a){b.getVolume(function(a){b.options.volume=a});b.fire("volumechange",a)})}a(b.$video)})}},{key:"init",value:function(){this.playerID="VideoWorker-"+this.ID}},{key:"loadAPI",value:function(){if(!p||!q){var a="";if("youtube"!==this.type||p||(p=1,a="https://www.youtube.com/iframe_api"),"vimeo"!==this.type||q||(q=1,a="https://player.vimeo.com/api/player.js"),a){var b=
document.createElement("script"),g=document.getElementsByTagName("head")[0];b.src=a;g.appendChild(b)}}}},{key:"onAPIready",value:function(a){if("youtube"===this.type&&("undefined"!=typeof YT&&0!==YT.loaded||t?"object"===("undefined"==typeof YT?"undefined":h(YT))&&1===YT.loaded?a():m.done(function(){a()}):(t=1,window.onYouTubeIframeAPIReady=function(){window.onYouTubeIframeAPIReady=null;m.resolve("done");a()})),"vimeo"===this.type)if("undefined"!=typeof Vimeo||l)"undefined"!=typeof Vimeo?a():g.done(function(){a()});
else{l=1;var b=setInterval(function(){"undefined"!=typeof Vimeo&&(clearInterval(b),g.resolve("done"),a())},20)}"local"===this.type&&a()}}]),a}();c.default=a},function(a,c,e){function d(a){return a&&a.__esModule?a:{default:a}}Object.defineProperty(c,"__esModule",{value:!0});c.default=function(){var a=0<arguments.length&&void 0!==arguments[0]?arguments[0]:n.default.jarallax;if(void 0!==a){a=a.constructor;var c=a.prototype.init;a.prototype.init=function(){var a=this;c.apply(a);a.video&&!a.options.disableVideo()&&
a.video.getVideo(function(g){var c=g.parentNode;a.css(g,{position:a.image.position,top:"0px",left:"0px",right:"0px",bottom:"0px",width:"100%",height:"100%",maxWidth:"none",maxHeight:"none",margin:0,zIndex:-1});a.$video=g;a.image.$container.appendChild(g);c.parentNode.removeChild(c)})};var d=a.prototype.coverImage;a.prototype.coverImage=function(){var a=d.apply(this),c=!!this.image.$item&&this.image.$item.nodeName;if(a&&this.video&&c&&("IFRAME"===c||"VIDEO"===c)){var f=a.image.height,b=f*this.image.width/
this.image.height,e=(a.container.width-b)/2,h=a.image.marginTop;a.container.width>b&&(f=(b=a.container.width)*this.image.height/this.image.width,e=0,h+=(a.image.height-f)/2);"IFRAME"===c&&(f+=400,h-=200);this.css(this.$video,{width:b+"px",marginLeft:e+"px",height:f+"px",marginTop:h+"px"})}return a};var e=a.prototype.initImg;a.prototype.initImg=function(){var a=e.apply(this);return this.options.videoSrc||(this.options.videoSrc=this.$item.getAttribute("data-jarallax-video")||null),this.options.videoSrc?
(this.defaultInitImgResult=a,!0):a};var l=a.prototype.canInitParallax;a.prototype.canInitParallax=function(){var a=this,c=l.apply(a);if(!a.options.videoSrc)return c;var d=new h.default(a.options.videoSrc,{autoplay:!0,loop:a.options.videoLoop,showContols:!1,startTime:a.options.videoStartTime||0,endTime:a.options.videoEndTime||0,mute:a.options.videoVolume?0:1,volume:a.options.videoVolume||0});if(d.isValid())if(c){if(d.on("ready",function(){if(a.options.videoPlayOnlyVisible){var b=a.onScroll;a.onScroll=
function(){b.apply(a);(a.options.videoLoop||!a.options.videoLoop&&!a.videoEnded)&&(a.isVisible()?d.play():d.pause())}}else d.play()}),d.on("started",function(){a.image.$default_item=a.image.$item;a.image.$item=a.$video;a.image.width=a.video.videoWidth||1280;a.image.height=a.video.videoHeight||720;a.coverImage();a.clipContainer();a.onScroll();a.image.$default_item&&(a.image.$default_item.style.display="none")}),d.on("ended",function(){a.videoEnded=!0;a.options.videoLoop||a.image.$default_item&&(a.image.$item=
a.image.$default_item,a.image.$item.style.display="block",a.coverImage(),a.clipContainer(),a.onScroll())}),a.video=d,!a.defaultInitImgResult)return"local"!==d.type?(d.getImageURL(function(b){a.image.src=b;a.init()}),!1):(a.image.src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7",!0)}else a.defaultInitImgResult||d.getImageURL(function(b){var c=a.$item.getAttribute("style");c&&a.$item.setAttribute("data-jarallax-original-styles",c);a.css(a.$item,{"background-image":'url("'+
b+'")',"background-position":"center","background-size":"cover"})});return c};var m=a.prototype.destroy;a.prototype.destroy=function(){this.image.$default_item&&(this.image.$item=this.image.$default_item,delete this.image.$default_item);m.apply(this)}}};var h=d(e(8)),n=d(e(4))}]);