/*
 Name    : Just Another Parallax [Jarallax]
 Version : 1.10.7
 Author  : nK <https://nkdev.info>
 GitHub  : https://github.com/nk-o/jarallax
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,c){a!=Array.prototype&&a!=Object.prototype&&(a[d]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var d=0;return $jscomp.iteratorPrototype(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.iteratorFromArray=function(a,d){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,e={next:function(){if(c<a.length){var l=c++;return{value:d(l,a[l]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,d,c,e){if(d){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var l=a[e];l in c||(c[l]={});c=c[l]}a=a[a.length-1];e=c[a];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
!function(a){function d(e){if(c[e])return c[e].exports;var l=c[e]={i:e,l:!1,exports:{}};return a[e].call(l.exports,l,l.exports,d),l.l=!0,l.exports}var c={};d.m=a;d.c=c;d.d=function(e,a,c){d.o(e,a)||Object.defineProperty(e,a,{enumerable:!0,get:c})};d.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"});Object.defineProperty(e,"__esModule",{value:!0})};d.t=function(e,a){if((1&a&&(e=d(e)),8&a)||4&a&&"object"==typeof e&&e&&e.__esModule)return e;
var c=Object.create(null);if(d.r(c),Object.defineProperty(c,"default",{enumerable:!0,value:e}),2&a&&"string"!=typeof e)for(var l in e)d.d(c,l,function(a){return e[a]}.bind(null,l));return c};d.n=function(a){var e=a&&a.__esModule?function(){return a.default}:function(){return a};return d.d(e,"a",e),e};d.o=function(a,d){return Object.prototype.hasOwnProperty.call(a,d)};d.p="";d(d.s=11)}([,,function(a,d,c){a.exports=function(a){"complete"===document.readyState||"interactive"===document.readyState?a.call():
document.attachEvent?document.attachEvent("onreadystatechange",function(){"interactive"===document.readyState&&a.call()}):document.addEventListener&&document.addEventListener("DOMContentLoaded",a)}},,function(a,d,c){d=c(5);a.exports="undefined"!=typeof window?window:void 0!==d?d:"undefined"!=typeof self?self:{}},function(a,d,c){c="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?
"symbol":typeof a};d=function(){return this}();try{d=d||Function("return this")()||(0,eval)("this")}catch(e){"object"===("undefined"==typeof window?"undefined":c(window))&&(d=window)}a.exports=d},,,,,,function(a,d,c){a.exports=c(12)},function(a,d,c){function e(a){return a&&a.__esModule?a:{default:a}}var l="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};
a=e(c(2));var h=c(4),p=e(c(13)),y=h.window.jarallax;if(h.window.jarallax=p.default,h.window.jarallax.noConflict=function(){return h.window.jarallax=y,this},void 0!==h.jQuery){c=function(){var a=arguments||[];Array.prototype.unshift.call(a,this);a=p.default.apply(h.window,a);return"object"!==(void 0===a?"undefined":l(a))?a:this};c.constructor=p.default.constructor;var z=h.jQuery.fn.jarallax;h.jQuery.fn.jarallax=c;h.jQuery.fn.jarallax.noConflict=function(){return h.jQuery.fn.jarallax=z,this}}(0,a.default)(function(){(0,
p.default)(document.querySelectorAll("[data-jarallax]"))})},function(a,d,c){(function(a){function e(a){return a&&a.__esModule?a:{default:a}}function h(a){v=n.window.innerWidth||document.documentElement.clientWidth;k=n.window.innerHeight||document.documentElement.clientHeight;"object"!==(void 0===a?"undefined":u(a))||"load"!==a.type&&"dom-loaded"!==a.type||(w=!0)}function p(){if(r.length){x=void 0!==n.window.pageYOffset?n.window.pageYOffset:(document.documentElement||document.body.parentNode||document.body).scrollTop;
var a=w||!t||t.width!==v||t.height!==k,g=A||a||!t||t.y!==x;A=w=!1;(a||g)&&(r.forEach(function(f){a&&f.onResize();g&&f.onScroll()}),t={width:v,height:k,y:x});(0,C.default)(p)}}Object.defineProperty(d,"__esModule",{value:!0});var y=function(){return function(a,g){if(Array.isArray(a))return a;if(Symbol.iterator in Object(a)){var f=[],b=!0,d=!1,c=void 0;try{for(var e,m=a[Symbol.iterator]();!(b=(e=m.next()).done)&&(f.push(e.value),!g||f.length!==g);b=!0);}catch(F){d=!0,c=F}finally{try{!b&&m.return&&m.return()}finally{if(d)throw c;
}}return f}throw new TypeError("Invalid attempt to destructure non-iterable instance");}}(),z=function(){function a(a,f){for(var b=0;b<f.length;b++){var g=f[b];g.enumerable=g.enumerable||!1;g.configurable=!0;"value"in g&&(g.writable=!0);Object.defineProperty(a,g.key,g)}}return function(g,f,b){return f&&a(g.prototype,f),b&&a(g,b),g}}(),u="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&
a!==Symbol.prototype?"symbol":typeof a},G=e(c(2)),C=e(c(14)),n=c(4),H=-1<navigator.userAgent.indexOf("MSIE ")||-1<navigator.userAgent.indexOf("Trident/")||-1<navigator.userAgent.indexOf("Edge/"),B=function(){for(var a=["transform","WebkitTransform","MozTransform"],g=document.createElement("div"),f=0;f<a.length;f++)if(g&&void 0!==g.style[a[f]])return a[f];return!1}(),v=void 0,k=void 0,x=void 0,w=!1,A=!1;h();n.window.addEventListener("resize",h);n.window.addEventListener("orientationchange",h);n.window.addEventListener("load",
h);(0,G.default)(function(){h({type:"dom-loaded"})});var r=[],t=!1,D=!!a.ResizeObserver&&new a.ResizeObserver(function(a){a&&a.length&&(0,C.default)(function(){a.forEach(function(a){a.target&&a.target.jarallax&&(w||a.target.jarallax.onResize(),A=!0)})})}),I=0,E=function(){function a(g,f){if(!(this instanceof a))throw new TypeError("Cannot call a class as a function");var b=this;b.instanceID=I++;b.$item=g;b.defaults={type:"scroll",speed:.5,imgSrc:null,imgElement:".jarallax-img",imgSize:"cover",imgPosition:"50% 50%",
imgRepeat:"no-repeat",keepImg:!1,elementInViewport:null,zIndex:-100,disableParallax:!1,disableVideo:!1,automaticResize:!0,videoSrc:null,videoStartTime:0,videoEndTime:0,videoVolume:0,videoLoop:!0,videoPlayOnlyVisible:!0,onScroll:null,onInit:null,onDestroy:null,onCoverImage:null};g=b.$item.getAttribute("data-jarallax");var d=JSON.parse(g||"{}");g&&console.warn("Detected usage of deprecated data-jarallax JSON options, you should use pure data-attribute options. See info here - https://github.com/nk-o/jarallax/issues/53");
var c=b.$item.dataset||{},e={};if(Object.keys(c).forEach(function(a){var g=a.substr(0,1).toLowerCase()+a.substr(1);g&&void 0!==b.defaults[g]&&(e[g]=c[a])}),b.options=b.extend({},b.defaults,d,e,f),b.pureOptions=b.extend({},b.options),Object.keys(b.options).forEach(function(a){"true"===b.options[a]?b.options[a]=!0:"false"===b.options[a]&&(b.options[a]=!1)}),b.options.speed=Math.min(2,Math.max(-1,parseFloat(b.options.speed))),(b.options.noAndroid||b.options.noIos)&&(console.warn("Detected usage of deprecated noAndroid or noIos options, you should use disableParallax option. See info here - https://github.com/nk-o/jarallax/#disable-on-mobile-devices"),
b.options.disableParallax||(b.options.noIos&&b.options.noAndroid?b.options.disableParallax=/iPad|iPhone|iPod|Android/:b.options.noIos?b.options.disableParallax=/iPad|iPhone|iPod/:b.options.noAndroid&&(b.options.disableParallax=/Android/))),"string"==typeof b.options.disableParallax&&(b.options.disableParallax=new RegExp(b.options.disableParallax)),b.options.disableParallax instanceof RegExp){var k=b.options.disableParallax;b.options.disableParallax=function(){return k.test(navigator.userAgent)}}if("function"!=
typeof b.options.disableParallax&&(b.options.disableParallax=function(){return!1}),"string"==typeof b.options.disableVideo&&(b.options.disableVideo=new RegExp(b.options.disableVideo)),b.options.disableVideo instanceof RegExp){var m=b.options.disableVideo;b.options.disableVideo=function(){return m.test(navigator.userAgent)}}"function"!=typeof b.options.disableVideo&&(b.options.disableVideo=function(){return!1});(f=b.options.elementInViewport)&&"object"===(void 0===f?"undefined":u(f))&&void 0!==f.length&&
(f=y(f,1)[0]);f instanceof Element||(f=null);b.options.elementInViewport=f;b.image={src:b.options.imgSrc||null,$container:null,useImgTag:!1,position:/iPad|iPhone|iPod|Android/.test(navigator.userAgent)?"absolute":"fixed"};b.initImg()&&b.canInitParallax()&&b.init()}return z(a,[{key:"css",value:function(a,f){return"string"==typeof f?n.window.getComputedStyle(a).getPropertyValue(f):(f.transform&&B&&(f[B]=f.transform),Object.keys(f).forEach(function(b){a.style[b]=f[b]}),a)}},{key:"extend",value:function(a){var g=
arguments;return a=a||{},Object.keys(arguments).forEach(function(b){g[b]&&Object.keys(g[b]).forEach(function(f){a[f]=g[b][f]})}),a}},{key:"getWindowData",value:function(){return{width:v,height:k,y:x}}},{key:"initImg",value:function(){var a=this.options.imgElement;return a&&"string"==typeof a&&(a=this.$item.querySelector(a)),a instanceof Element||(a=null),a&&(this.options.keepImg?this.image.$item=a.cloneNode(!0):(this.image.$item=a,this.image.$itemParent=a.parentNode),this.image.useImgTag=!0),!(!this.image.$item&&
(null===this.image.src&&(this.image.src=this.css(this.$item,"background-image").replace(/^url\(['"]?/g,"").replace(/['"]?\)$/g,"")),!this.image.src||"none"===this.image.src))}},{key:"canInitParallax",value:function(){return B&&!this.options.disableParallax()}},{key:"init",value:function(){var a={position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden",pointerEvents:"none"},f={};if(!this.options.keepImg){var b=this.$item.getAttribute("style");(b&&this.$item.setAttribute("data-jarallax-original-styles",
b),this.image.useImgTag)&&(b=this.image.$item.getAttribute("style"))&&this.image.$item.setAttribute("data-jarallax-original-styles",b)}if("static"===this.css(this.$item,"position")&&this.css(this.$item,{position:"relative"}),"auto"===this.css(this.$item,"z-index")&&this.css(this.$item,{zIndex:0}),this.image.$container=document.createElement("div"),this.css(this.image.$container,a),this.css(this.image.$container,{"z-index":this.options.zIndex}),H&&this.css(this.image.$container,{opacity:.9999}),this.image.$container.setAttribute("id",
"jarallax-container-"+this.instanceID),this.$item.appendChild(this.image.$container),this.image.useImgTag?f=this.extend({"object-fit":this.options.imgSize,"object-position":this.options.imgPosition,"font-family":"object-fit: "+this.options.imgSize+"; object-position: "+this.options.imgPosition+";","max-width":"none"},a,f):(this.image.$item=document.createElement("div"),this.image.src&&(f=this.extend({"background-position":this.options.imgPosition,"background-size":this.options.imgSize,"background-repeat":this.options.imgRepeat,
"background-image":'url("'+this.image.src+'")'},a,f))),"opacity"!==this.options.type&&"scale"!==this.options.type&&"scale-opacity"!==this.options.type&&1!==this.options.speed||(this.image.position="absolute"),"fixed"===this.image.position)for(a=0,b=this.$item;null!==b&&b!==document&&0===a;){var d=this.css(b,"-webkit-transform")||this.css(b,"-moz-transform")||this.css(b,"transform");d&&"none"!==d&&(a=1,this.image.position="absolute");b=b.parentNode}f.position=this.image.position;this.css(this.image.$item,
f);this.image.$container.appendChild(this.image.$item);this.onResize();this.onScroll(!0);this.options.automaticResize&&D&&D.observe(this.$item);this.options.onInit&&this.options.onInit.call(this);"none"!==this.css(this.$item,"background-image")&&this.css(this.$item,{"background-image":"none"});this.addToParallaxList()}},{key:"addToParallaxList",value:function(){r.push(this);1===r.length&&p()}},{key:"removeFromParallaxList",value:function(){var a=this;r.forEach(function(f,b){f.instanceID===a.instanceID&&
r.splice(b,1)})}},{key:"destroy",value:function(){this.removeFromParallaxList();var a=this.$item.getAttribute("data-jarallax-original-styles");if(this.$item.removeAttribute("data-jarallax-original-styles"),a?this.$item.setAttribute("style",a):this.$item.removeAttribute("style"),this.image.useImgTag){var f=this.image.$item.getAttribute("data-jarallax-original-styles");this.image.$item.removeAttribute("data-jarallax-original-styles");f?this.image.$item.setAttribute("style",a):this.image.$item.removeAttribute("style");
this.image.$itemParent&&this.image.$itemParent.appendChild(this.image.$item)}this.$clipStyles&&this.$clipStyles.parentNode.removeChild(this.$clipStyles);this.image.$container&&this.image.$container.parentNode.removeChild(this.image.$container);this.options.onDestroy&&this.options.onDestroy.call(this);delete this.$item.jarallax}},{key:"clipContainer",value:function(){if("fixed"===this.image.position){var a=this.image.$container.getBoundingClientRect(),f=a.width;a=a.height;this.$clipStyles||(this.$clipStyles=
document.createElement("style"),this.$clipStyles.setAttribute("type","text/css"),this.$clipStyles.setAttribute("id","jarallax-clip-"+this.instanceID),(document.head||document.getElementsByTagName("head")[0]).appendChild(this.$clipStyles));f="#jarallax-container-"+this.instanceID+" {\n           clip: rect(0 "+f+"px "+a+"px 0);\n           clip: rect(0, "+f+"px, "+a+"px, 0);\n        }";this.$clipStyles.styleSheet?this.$clipStyles.styleSheet.cssText=f:this.$clipStyles.innerHTML=f}}},{key:"coverImage",
value:function(){var a=this.image.$container.getBoundingClientRect(),f=a.height,b=this.options.speed,d="scroll"===this.options.type||"scroll-opacity"===this.options.type,c=0,e=f,m=0;return d&&(0>b?(c=b*Math.max(f,k),k<f&&(c-=b*(f-k))):c=b*(f+k),1<b?e=Math.abs(c-k):0>b?e=c/b+Math.abs(c):e+=(k-f)*(1-b),c/=2),this.parallaxScrollDistance=c,m=d?(k-e)/2:(f-e)/2,this.css(this.image.$item,{height:e+"px",marginTop:m+"px",left:"fixed"===this.image.position?a.left+"px":"0",width:a.width+"px"}),this.options.onCoverImage&&
this.options.onCoverImage.call(this),{image:{height:e,marginTop:m},container:a}}},{key:"isVisible",value:function(){return this.isElementInViewport||!1}},{key:"onScroll",value:function(a){var d=this.$item.getBoundingClientRect(),b=d.top,c=d.height,e={},g=d;if(this.options.elementInViewport&&(g=this.options.elementInViewport.getBoundingClientRect()),this.isElementInViewport=0<=g.bottom&&0<=g.right&&g.top<=k&&g.left<=v,a||this.isElementInViewport){a=Math.max(0,b);g=Math.max(0,c+b);var m=Math.max(0,
-b),l=Math.max(0,b+c-k),h=Math.max(0,c-(b+c-k)),p=Math.max(0,-b+k-c),n=1-2*(k-b)/(k+c),q=1;if(c<k?q=1-(m||l)/c:g<=k?q=g/k:h<=k&&(q=h/k),"opacity"!==this.options.type&&"scale-opacity"!==this.options.type&&"scroll-opacity"!==this.options.type||(e.transform="translate3d(0,0,0)",e.opacity=q),"scale"===this.options.type||"scale-opacity"===this.options.type)c=1,0>this.options.speed?c-=this.options.speed*q:c+=this.options.speed*(1-q),e.transform="scale("+c+") translate3d(0,0,0)";if("scroll"===this.options.type||
"scroll-opacity"===this.options.type)c=this.parallaxScrollDistance*n,"absolute"===this.image.position&&(c-=b),e.transform="translate3d(0,"+c+"px,0)";this.css(this.image.$item,e);this.options.onScroll&&this.options.onScroll.call(this,{section:d,beforeTop:a,beforeTopEnd:g,afterTop:m,beforeBottom:l,beforeBottomEnd:h,afterBottom:p,visiblePercent:q,fromViewportCenter:n})}}},{key:"onResize",value:function(){this.coverImage();this.clipContainer()}}]),a}();a=function(a){("object"===("undefined"==typeof HTMLElement?
"undefined":u(HTMLElement))?a instanceof HTMLElement:a&&"object"===(void 0===a?"undefined":u(a))&&null!==a&&1===a.nodeType&&"string"==typeof a.nodeName)&&(a=[a]);for(var c=arguments[1],d=Array.prototype.slice.call(arguments,2),b=a.length,e=0,h=void 0;e<b;e++)if("object"===(void 0===c?"undefined":u(c))||void 0===c?a[e].jarallax||(a[e].jarallax=new E(a[e],c)):a[e].jarallax&&(h=a[e].jarallax[c].apply(a[e].jarallax,d)),void 0!==h)return h;return a};a.constructor=E;d.default=a}).call(this,c(5))},function(a,
d,c){function e(a){var c=+new Date;a=setTimeout(a,Math.max(0,16-(c-l)));return l=c,a}d=c(4);c=d.requestAnimationFrame||d.webkitRequestAnimationFrame||d.mozRequestAnimationFrame||e;var l=+new Date,h=d.cancelAnimationFrame||d.webkitCancelAnimationFrame||d.mozCancelAnimationFrame||clearTimeout;Function.prototype.bind&&(c=c.bind(d),h=h.bind(d));(a.exports=c).cancel=h}]);