/*
 Name    : Elements Extension for Jarallax
 Version : 1.0.0
 Author  : nK <https://nkdev.info>
 GitHub  : https://github.com/nk-o/jarallax
*/
!function(e){function b(a){if(d[a])return d[a].exports;var c=d[a]={i:a,l:!1,exports:{}};return e[a].call(c.exports,c,c.exports,b),c.l=!0,c.exports}var d={};b.m=e;b.c=d;b.d=function(a,c,d){b.o(a,c)||Object.defineProperty(a,c,{enumerable:!0,get:d})};b.r=function(a){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(a,Symbol.toStringTag,{value:"Module"});Object.defineProperty(a,"__esModule",{value:!0})};b.t=function(a,c){if((1&c&&(a=b(a)),8&c)||4&c&&"object"==typeof a&&a&&a.__esModule)return a;
var d=Object.create(null);if(b.r(d),Object.defineProperty(d,"default",{enumerable:!0,value:a}),2&c&&"string"!=typeof a)for(var e in a)b.d(d,e,function(b){return a[b]}.bind(null,e));return d};b.n=function(a){var c=a&&a.__esModule?function(){return a.default}:function(){return a};return b.d(c,"a",c),c};b.o=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};b.p="";b(b.s=0)}([function(e,b,d){e.exports=d(1)},function(e,b,d){function a(a){return a&&a.__esModule?a:{default:a}}e=a(d(2));(0,a(d(3)).default)();
(0,e.default)(function(){"undefined"!=typeof jarallax&&jarallax(document.querySelectorAll("[data-jarallax-element]"))})},function(e,b,d){e.exports=function(a){"complete"===document.readyState||"interactive"===document.readyState?a.call():document.attachEvent?document.attachEvent("onreadystatechange",function(){"interactive"===document.readyState&&a.call()}):document.addEventListener&&document.addEventListener("DOMContentLoaded",a)}},function(e,b,d){Object.defineProperty(b,"__esModule",{value:!0});
b.default=function(){var b=0<arguments.length&&void 0!==arguments[0]?arguments[0]:a.default.jarallax;if(void 0!==b){var d=b.constructor;"initImg canInitParallax init destroy clipContainer coverImage isVisible onScroll onResize".split(" ").forEach(function(a){var b=d.prototype[a];d.prototype[a]=function(){var d=arguments||[];if("initImg"===a&&null!==this.$item.getAttribute("data-jarallax-element")&&(this.options.type="element",this.pureOptions.speed=this.$item.getAttribute("data-jarallax-element")||
this.pureOptions.speed),"element"!==this.options.type)return b.apply(this,d);switch(this.pureOptions.threshold=this.$item.getAttribute("data-threshold")||"",a){case "init":var c=this.pureOptions.speed.split(" ");this.options.speed=this.pureOptions.speed||0;this.options.speedY=c[0]?parseFloat(c[0]):0;this.options.speedX=c[1]?parseFloat(c[1]):0;c=this.pureOptions.threshold.split(" ");this.options.thresholdY=c[0]?parseFloat(c[0]):null;this.options.thresholdX=c[1]?parseFloat(c[1]):null;break;case "onResize":c=
this.css(this.$item,"transform");this.css(this.$item,{transform:""});var e=this.$item.getBoundingClientRect();this.itemData={width:e.width,height:e.height,y:e.top+this.getWindowData().y,x:e.left};this.css(this.$item,{transform:c});break;case "onScroll":c=this.getWindowData();e=(c.y+c.height/2-this.itemData.y-this.itemData.height/2)/(c.height/2);c=e*this.options.speedY;e*=this.options.speedX;var f=c,g=e;null!==this.options.thresholdY&&c>this.options.thresholdY&&(f=0);null!==this.options.thresholdX&&
e>this.options.thresholdX&&(g=0);this.css(this.$item,{transform:"translate3d("+g+"px,"+f+"px,0)"});break;case "initImg":case "isVisible":case "clipContainer":case "coverImage":return!0}return b.apply(this,d)}})}};var a=function(a){return a&&a.__esModule?a:{default:a}}(d(4))},function(e,b,d){b=d(5);e.exports="undefined"!=typeof window?window:void 0!==b?b:"undefined"!=typeof self?self:{}},function(e,b,d){d="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&
"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a};b=function(){return this}();try{b=b||Function("return this")()||(0,eval)("this")}catch(a){"object"===("undefined"==typeof window?"undefined":d(window))&&(b=window)}e.exports=b}]);