/*
 Magnific Popup - v1.1.0 - 2016-02-20
 http://dimsemenov.com/plugins/magnific-popup/
 Copyright (c) 2016 Dmitry Semenov; */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(e,a,m){e instanceof String&&(e=String(e));for(var h=e.length,l=0;l<h;l++){var n=e[l];if(a.call(m,n,l,e))return{i:l,v:n}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,a,m){e!=Array.prototype&&e!=Object.prototype&&(e[a]=m.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,a,m,h){if(a){m=$jscomp.global;e=e.split(".");for(h=0;h<e.length-1;h++){var l=e[h];l in m||(m[l]={});m=m[l]}e=e[e.length-1];h=m[e];a=a(h);a!=h&&null!=a&&$jscomp.defineProperty(m,e,{configurable:!0,writable:!0,value:a})}};
$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6","es3");
!function(e){"function"==typeof define&&define.amd?define(["jquery"],e):"object"==typeof exports?e(require("jquery")):e(window.jQuery||window.Zepto)}(function(e){var a,m,h,l,n,G,v=function(){},z=!!window.jQuery,q=e(window),g=function(b,c){a.ev.on("mfp"+b+".mfp",c)},r=function(a,c,d,f){var b=document.createElement("div");return b.className="mfp-"+a,d&&(b.innerHTML=d),f?c&&c.appendChild(b):(b=e(b),c&&b.appendTo(c)),b},k=function(b,c){a.ev.triggerHandler("mfp"+b,c);a.st.callbacks&&(b=b.charAt(0).toLowerCase()+
b.slice(1),a.st.callbacks[b]&&a.st.callbacks[b].apply(a,e.isArray(c)?c:[c]))},A=function(b){return b===G&&a.currTemplate.closeBtn||(a.currTemplate.closeBtn=e(a.st.closeMarkup.replace("%title%",a.st.tClose)),G=b),a.currTemplate.closeBtn},B=function(){e.magnificPopup.instance||((a=new v).init(),e.magnificPopup.instance=a)},K=function(){var a=document.createElement("p").style,c=["ms","O","Moz","Webkit"];if(void 0!==a.transition)return!0;for(;c.length;)if(c.pop()+"Transition"in a)return!0;return!1};v.prototype=
{constructor:v,init:function(){var b=navigator.appVersion;a.isLowIE=a.isIE8=document.all&&!document.addEventListener;a.isAndroid=/android/gi.test(b);a.isIOS=/iphone|ipad|ipod/gi.test(b);a.supportsTransition=K();a.probablyMobile=a.isAndroid||a.isIOS||/(Opera Mini)|Kindle|webOS|BlackBerry|(Opera Mobi)|(Windows Phone)|IEMobile/i.test(navigator.userAgent);h=e(document);a.popupsCache={}},open:function(b){var c;if(!1===b.isObj){a.items=b.items.toArray();a.index=0;var d,f=b.items;for(c=0;c<f.length;c++)if((d=
f[c]).parsed&&(d=d.el[0]),d===b.el[0]){a.index=c;break}}else a.items=e.isArray(b.items)?b.items:[b.items],a.index=b.index||0;if(!a.isOpen){a.types=[];n="";b.mainEl&&b.mainEl.length?a.ev=b.mainEl.eq(0):a.ev=h;b.key?(a.popupsCache[b.key]||(a.popupsCache[b.key]={}),a.currTemplate=a.popupsCache[b.key]):a.currTemplate={};a.st=e.extend(!0,{},e.magnificPopup.defaults,b);a.fixedContentPos="auto"===a.st.fixedContentPos?!a.probablyMobile:a.st.fixedContentPos;a.st.modal&&(a.st.closeOnContentClick=!1,a.st.closeOnBgClick=
!1,a.st.showCloseBtn=!1,a.st.enableEscapeKey=!1);a.bgOverlay||(a.bgOverlay=r("bg").on("click.mfp",function(){a.close()}),a.wrap=r("wrap").attr("tabindex",-1).on("click.mfp",function(b){a._checkIfClose(b.target)&&a.close()}),a.container=r("container",a.wrap));a.contentContainer=r("content");a.st.preloader&&(a.preloader=r("preloader",a.container,a.st.tLoading));d=e.magnificPopup.modules;for(c=0;c<d.length;c++)f=d[c],f=f.charAt(0).toUpperCase()+f.slice(1),a["init"+f].call(a);k("BeforeOpen");a.st.showCloseBtn&&
(a.st.closeBtnInside?(g("MarkupParse",function(a,b,c,d){c.close_replaceWith=A(d.type)}),n+=" mfp-close-btn-in"):a.wrap.append(A()));a.st.alignTop&&(n+=" mfp-align-top");a.fixedContentPos?a.wrap.css({overflow:a.st.overflowY,overflowX:"hidden",overflowY:a.st.overflowY}):a.wrap.css({top:q.scrollTop(),position:"absolute"});(!1===a.st.fixedBgPos||"auto"===a.st.fixedBgPos&&!a.fixedContentPos)&&a.bgOverlay.css({height:h.height(),position:"absolute"});a.st.enableEscapeKey&&h.on("keyup.mfp",function(b){27===
b.keyCode&&a.close()});q.on("resize.mfp",function(){a.updateSize()});a.st.closeOnContentClick||(n+=" mfp-auto-cursor");n&&a.wrap.addClass(n);c=a.wH=q.height();d={};a.fixedContentPos&&a._hasScrollBar(c)&&(f=a._getScrollbarSize())&&(d.marginRight=f);a.fixedContentPos&&(a.isIE7?e("body, html").css("overflow","hidden"):d.overflow="hidden");f=a.st.mainClass;return a.isIE7&&(f+=" mfp-ie7"),f&&a._addClassToMFP(f),a.updateItemHTML(),k("BuildControls"),e("html").css(d),a.bgOverlay.add(a.wrap).prependTo(a.st.prependTo||
e(document.body)),a._lastFocusedEl=document.activeElement,setTimeout(function(){a.content?(a._addClassToMFP("mfp-ready"),a._setFocus()):a.bgOverlay.addClass("mfp-ready");h.on("focusin.mfp",a._onFocusIn)},16),a.isOpen=!0,a.updateSize(c),k("Open"),b}a.updateItemHTML()},close:function(){a.isOpen&&(k("BeforeClose"),a.isOpen=!1,a.st.removalDelay&&!a.isLowIE&&a.supportsTransition?(a._addClassToMFP("mfp-removing"),setTimeout(function(){a._close()},a.st.removalDelay)):a._close())},_close:function(){k("Close");
var b="mfp-removing mfp-ready ";if(a.bgOverlay.detach(),a.wrap.detach(),a.container.empty(),a.st.mainClass&&(b+=a.st.mainClass+" "),a._removeClassFromMFP(b),a.fixedContentPos)b={marginRight:""},a.isIE7?e("body, html").css("overflow",""):b.overflow="",e("html").css(b);h.off("keyup.mfp focusin.mfp");a.ev.off(".mfp");a.wrap.attr("class","mfp-wrap").removeAttr("style");a.bgOverlay.attr("class","mfp-bg");a.container.attr("class","mfp-container");!a.st.showCloseBtn||a.st.closeBtnInside&&!0!==a.currTemplate[a.currItem.type]||
a.currTemplate.closeBtn&&a.currTemplate.closeBtn.detach();a.st.autoFocusLast&&a._lastFocusedEl&&e(a._lastFocusedEl).focus();a.currItem=null;a.content=null;a.currTemplate=null;a.prevHeight=0;k("AfterClose")},updateSize:function(b){a.isIOS?(b=document.documentElement.clientWidth/window.innerWidth*window.innerHeight,a.wrap.css("height",b),a.wH=b):a.wH=b||q.height();a.fixedContentPos||a.wrap.css("height",a.wH);k("Resize")},updateItemHTML:function(){var b=a.items[a.index];a.contentContainer.detach();a.content&&
a.content.detach();b.parsed||(b=a.parseEl(a.index));var c=b.type;if(k("BeforeChange",[a.currItem?a.currItem.type:"",c]),a.currItem=b,!a.currTemplate[c]){var d=!!a.st[c]&&a.st[c].markup;k("FirstMarkupParse",d);a.currTemplate[c]=!d||e(d)}l&&l!==b.type&&a.container.removeClass("mfp-"+l+"-holder");d=a["get"+c.charAt(0).toUpperCase()+c.slice(1)](b,a.currTemplate[c]);a.appendContent(d,c);b.preloaded=!0;k("Change",b);l=b.type;a.container.prepend(a.contentContainer);k("AfterChange")},appendContent:function(b,
c){(a.content=b)?a.st.showCloseBtn&&a.st.closeBtnInside&&!0===a.currTemplate[c]?a.content.find(".mfp-close").length||a.content.append(A()):a.content=b:a.content="";k("BeforeAppend");a.container.addClass("mfp-"+c+"-holder");a.contentContainer.append(a.content)},parseEl:function(b){var c,d=a.items[b];if(d.tagName?d={el:e(d)}:(c=d.type,d={data:d,src:d.src}),d.el){for(var f=a.types,w=0;w<f.length;w++)if(d.el.hasClass("mfp-"+f[w])){c=f[w];break}d.src=d.el.attr("data-mfp-src");d.src||(d.src=d.el.attr("href"))}return d.type=
c||a.st.type||"inline",d.index=b,d.parsed=!0,a.items[b]=d,k("ElementParse",d),a.items[b]},addGroup:function(b,c){var d=function(d){d.mfpEl=this;a._openClick(d,b,c)};c||(c={});c.mainEl=b;c.items?(c.isObj=!0,b.off("click.magnificPopup").on("click.magnificPopup",d)):(c.isObj=!1,c.delegate?b.off("click.magnificPopup").on("click.magnificPopup",c.delegate,d):(c.items=b,b.off("click.magnificPopup").on("click.magnificPopup",d)))},_openClick:function(b,c,d){if((void 0!==d.midClick?d.midClick:e.magnificPopup.defaults.midClick)||
!(2===b.which||b.ctrlKey||b.metaKey||b.altKey||b.shiftKey)){var f=void 0!==d.disableOn?d.disableOn:e.magnificPopup.defaults.disableOn;if(f)if(e.isFunction(f)){if(!f.call(a))return!0}else if(q.width()<f)return!0;b.type&&(b.preventDefault(),a.isOpen&&b.stopPropagation());d.el=e(b.mfpEl);d.delegate&&(d.items=c.find(d.delegate));a.open(d)}},updateStatus:function(b,c){a.preloader&&(m!==b&&a.container.removeClass("mfp-s-"+m),c||"loading"!==b||(c=a.st.tLoading),c={status:b,text:c},k("UpdateStatus",c),b=
c.status,c=c.text,a.preloader.html(c),a.preloader.find("a").on("click",function(a){a.stopImmediatePropagation()}),a.container.addClass("mfp-s-"+b),m=b)},_checkIfClose:function(b){if(!e(b).hasClass("mfp-prevent-close")){var c=a.st.closeOnContentClick,d=a.st.closeOnBgClick;if(c&&d||!a.content||e(b).hasClass("mfp-close")||a.preloader&&b===a.preloader[0])return!0;if(b===a.content[0]||e.contains(a.content[0],b)){if(c)return!0}else if(d&&e.contains(document,b))return!0;return!1}},_addClassToMFP:function(b){a.bgOverlay.addClass(b);
a.wrap.addClass(b)},_removeClassFromMFP:function(b){this.bgOverlay.removeClass(b);a.wrap.removeClass(b)},_hasScrollBar:function(b){return(a.isIE7?h.height():document.body.scrollHeight)>(b||q.height())},_setFocus:function(){(a.st.focus?a.content.find(a.st.focus).eq(0):a.wrap).focus()},_onFocusIn:function(b){if(b.target!==a.wrap[0]&&!e.contains(a.wrap[0],b.target))return a._setFocus(),!1},_parseMarkup:function(a,c,d){var b;d.data&&(c=e.extend(d.data,c));k("MarkupParse",[a,c,d]);e.each(c,function(c,
d){if(void 0===d||!1===d)return!0;if(1<(b=c.split("_")).length){if(c=a.find(".mfp-"+b[0]),0<c.length){var f=b[1];"replaceWith"===f?c[0]!==d[0]&&c.replaceWith(d):"img"===f?c.is("img")?c.attr("src",d):c.replaceWith(e("\x3cimg\x3e").attr("src",d).attr("class",c.attr("class"))):c.attr(b[1],d)}}else a.find(".mfp-"+c).html(d)})},_getScrollbarSize:function(){if(void 0===a.scrollbarSize){var b=document.createElement("div");b.style.cssText="width: 99px; height: 99px; overflow: scroll; position: absolute; top: -9999px;";
document.body.appendChild(b);a.scrollbarSize=b.offsetWidth-b.clientWidth;document.body.removeChild(b)}return a.scrollbarSize}};e.magnificPopup={instance:null,proto:v.prototype,modules:[],open:function(a,c){return B(),(a=a?e.extend(!0,{},a):{}).isObj=!0,a.index=c||0,this.instance.open(a)},close:function(){return e.magnificPopup.instance&&e.magnificPopup.instance.close()},registerModule:function(a,c){c.options&&(e.magnificPopup.defaults[a]=c.options);e.extend(this.proto,c.proto);this.modules.push(a)},
defaults:{disableOn:0,key:null,midClick:!1,mainClass:"",preloader:!0,focus:"",closeOnContentClick:!1,closeOnBgClick:!0,closeBtnInside:!0,showCloseBtn:!0,enableEscapeKey:!0,modal:!1,alignTop:!1,removalDelay:0,prependTo:null,fixedContentPos:"auto",fixedBgPos:"auto",overflowY:"auto",closeMarkup:'\x3cbutton title\x3d"%title%" type\x3d"button" class\x3d"mfp-close"\x3e\x26#215;\x3c/button\x3e',tClose:"Close (Esc)",tLoading:"Loading...",autoFocusLast:!0}};e.fn.magnificPopup=function(b){B();var c=e(this);
if("string"==typeof b)if("open"===b){var d,f=z?c.data("magnificPopup"):c[0].magnificPopup,k=parseInt(arguments[1],10)||0;f.items?d=f.items[k]:(d=c,f.delegate&&(d=d.find(f.delegate)),d=d.eq(k));a._openClick({mfpEl:d},c,f)}else a.isOpen&&a[b].apply(a,Array.prototype.slice.call(arguments,1));else b=e.extend(!0,{},b),z?c.data("magnificPopup",b):c[0].magnificPopup=b,a.addGroup(c,b);return c};var t,x,y,H=function(){y&&(x.after(y.addClass(t)).detach(),y=null)};e.magnificPopup.registerModule("inline",{options:{hiddenClass:"hide",
markup:"",tNotFound:"Content not found"},proto:{initInline:function(){a.types.push("inline");g("Close.inline",function(){H()})},getInline:function(b,c){if(H(),b.src){c=a.st.inline;var d=e(b.src);if(d.length){var f=d[0].parentNode;f&&f.tagName&&(x||(t=c.hiddenClass,x=r(t),t="mfp-"+t),y=d.after(x).detach().removeClass(t));a.updateStatus("ready")}else a.updateStatus("error",c.tNotFound),d=e("\x3cdiv\x3e");return b.inlineElement=d,d}return a.updateStatus("ready"),a._parseMarkup(c,{},b),c}}});var u,C=
function(){u&&e(document.body).removeClass(u)},I=function(){C();a.req&&a.req.abort()};e.magnificPopup.registerModule("ajax",{options:{settings:null,cursor:"mfp-ajax-cur",tError:'\x3ca href\x3d"%url%"\x3eThe content\x3c/a\x3e could not be loaded.'},proto:{initAjax:function(){a.types.push("ajax");u=a.st.ajax.cursor;g("Close.ajax",I);g("BeforeChange.ajax",I)},getAjax:function(b){u&&e(document.body).addClass(u);a.updateStatus("loading");var c=e.extend({url:b.src,success:function(c,f,g){c={data:c,xhr:g};
k("ParseAjax",c);a.appendContent(e(c.data),"ajax");b.finished=!0;C();a._setFocus();setTimeout(function(){a.wrap.addClass("mfp-ready")},16);a.updateStatus("ready");k("AjaxContentAdded")},error:function(){C();b.finished=b.loadError=!0;a.updateStatus("error",a.st.ajax.tError.replace("%url%",b.src))}},a.st.ajax.settings);return a.req=e.ajax(c),""}}});var p,L=function(b){if(b.data&&void 0!==b.data.title)return b.data.title;var c=a.st.image.titleSrc;if(c){if(e.isFunction(c))return c.call(a,b);if(b.el)return b.el.attr(c)||
""}return""};e.magnificPopup.registerModule("image",{options:{markup:'\x3cdiv class\x3d"mfp-figure"\x3e\x3cdiv class\x3d"mfp-close"\x3e\x3c/div\x3e\x3cfigure\x3e\x3cdiv class\x3d"mfp-img"\x3e\x3c/div\x3e\x3cfigcaption\x3e\x3cdiv class\x3d"mfp-bottom-bar"\x3e\x3cdiv class\x3d"mfp-title"\x3e\x3c/div\x3e\x3cdiv class\x3d"mfp-counter"\x3e\x3c/div\x3e\x3c/div\x3e\x3c/figcaption\x3e\x3c/figure\x3e\x3c/div\x3e',cursor:"mfp-zoom-out-cur",titleSrc:"title",verticalFit:!0,tError:'\x3ca href\x3d"%url%"\x3eThe image\x3c/a\x3e could not be loaded.'},
proto:{initImage:function(){var b=a.st.image;a.types.push("image");g("Open.image",function(){"image"===a.currItem.type&&b.cursor&&e(document.body).addClass(b.cursor)});g("Close.image",function(){b.cursor&&e(document.body).removeClass(b.cursor);q.off("resize.mfp")});g("Resize.image",a.resizeImage);a.isLowIE&&g("AfterChange",a.resizeImage)},resizeImage:function(){var b=a.currItem;if(b&&b.img&&a.st.image.verticalFit){var c=0;a.isLowIE&&(c=parseInt(b.img.css("padding-top"),10)+parseInt(b.img.css("padding-bottom"),
10));b.img.css("max-height",a.wH-c)}},_onImageHasSize:function(b){b.img&&(b.hasSize=!0,p&&clearInterval(p),b.isCheckingImgSize=!1,k("ImageHasSize",b),b.imgHidden&&(a.content&&a.content.removeClass("mfp-loading"),b.imgHidden=!1))},findImageSize:function(b){var c=0,d=b.img[0],e=function(f){p&&clearInterval(p);p=setInterval(function(){0<d.naturalWidth?a._onImageHasSize(b):(200<c&&clearInterval(p),3==++c?e(10):40===c?e(50):100===c&&e(500))},f)};e(1)},getImage:function(b,c){var d=0,f=function(){b&&(b.img[0].complete?
(b.img.off(".mfploader"),b===a.currItem&&(a._onImageHasSize(b),a.updateStatus("ready")),b.hasSize=!0,b.loaded=!0,k("ImageLoadComplete")):200>++d?setTimeout(f,100):g())},g=function(){b&&(b.img.off(".mfploader"),b===a.currItem&&(a._onImageHasSize(b),a.updateStatus("error",h.tError.replace("%url%",b.src))),b.hasSize=!0,b.loaded=!0,b.loadError=!0)},h=a.st.image,m=c.find(".mfp-img");if(m.length){var l=document.createElement("img");l.className="mfp-img";b.el&&b.el.find("img").length&&(l.alt=b.el.find("img").attr("alt"));
b.img=e(l).on("load.mfploader",f).on("error.mfploader",g);l.src=b.src;m.is("img")&&(b.img=b.img.clone());0<(l=b.img[0]).naturalWidth?b.hasSize=!0:l.width||(b.hasSize=!1)}return a._parseMarkup(c,{title:L(b),img_replaceWith:b.img},b),a.resizeImage(),b.hasSize?(p&&clearInterval(p),b.loadError?(c.addClass("mfp-loading"),a.updateStatus("error",h.tError.replace("%url%",b.src))):(c.removeClass("mfp-loading"),a.updateStatus("ready")),c):(a.updateStatus("loading"),b.loading=!0,b.hasSize||(b.imgHidden=!0,c.addClass("mfp-loading"),
a.findImageSize(b)),c)}}});var D;e.magnificPopup.registerModule("zoom",{options:{enabled:!1,easing:"ease-in-out",duration:300,opener:function(a){return a.is("img")?a:a.find("img")}},proto:{initZoom:function(){var b,c=a.st.zoom;if(c.enabled&&a.supportsTransition){var d,e,h=c.duration,l=function(a){a=a.clone().removeAttr("style").removeAttr("class").addClass("mfp-animated-image");var b={position:"fixed",zIndex:9999,left:0,top:0,"-webkit-backface-visibility":"hidden"};return b["-webkit-transition"]=
b["-moz-transition"]=b["-o-transition"]=b.transition="all "+c.duration/1E3+"s "+c.easing,a.css(b),a},m=function(){a.content.css("visibility","visible")};g("BuildControls.zoom",function(){if(a._allowZoom()){if(clearTimeout(d),a.content.css("visibility","hidden"),!(b=a._getItemToZoom()))return void m();(e=l(b)).css(a._getOffset());a.wrap.append(e);d=setTimeout(function(){e.css(a._getOffset(!0));d=setTimeout(function(){m();setTimeout(function(){e.remove();b=e=null;k("ZoomAnimationEnded")},16)},h)},16)}});
g("BeforeClose.zoom",function(){if(a._allowZoom()){if(clearTimeout(d),a.st.removalDelay=h,!b){if(!(b=a._getItemToZoom()))return;e=l(b)}e.css(a._getOffset(!0));a.wrap.append(e);a.content.css("visibility","hidden");setTimeout(function(){e.css(a._getOffset())},16)}});g("Close.zoom",function(){a._allowZoom()&&(m(),e&&e.remove(),b=null)})}},_allowZoom:function(){return"image"===a.currItem.type},_getItemToZoom:function(){return!!a.currItem.hasSize&&a.currItem.img},_getOffset:function(b){var c;b=(c=b?a.currItem.img:
a.st.zoom.opener(a.currItem.el||a.currItem)).offset();var d=parseInt(c.css("padding-top"),10),f=parseInt(c.css("padding-bottom"),10);b.top-=e(window).scrollTop()-d;c={width:c.width(),height:(z?c.innerHeight():c[0].offsetHeight)-f-d};return(void 0===D&&(D=void 0!==document.createElement("p").style.MozTransform),D)?c["-moz-transform"]=c.transform="translate("+b.left+"px,"+b.top+"px)":(c.left=b.left,c.top=b.top),c}}});var E=function(b){if(a.currTemplate.iframe){var c=a.currTemplate.iframe.find("iframe");
c.length&&(b||(c[0].src="//about:blank"),a.isIE8&&c.css("display",b?"block":"none"))}};e.magnificPopup.registerModule("iframe",{options:{markup:'\x3cdiv class\x3d"mfp-iframe-scaler"\x3e\x3cdiv class\x3d"mfp-close"\x3e\x3c/div\x3e\x3ciframe class\x3d"mfp-iframe" src\x3d"//about:blank" frameborder\x3d"0" allowfullscreen\x3e\x3c/iframe\x3e\x3c/div\x3e',srcAction:"iframe_src",patterns:{youtube:{index:"youtube.com",id:"v\x3d",src:"https://www.youtube.com/embed/%id%?autoplay\x3d1"},vimeo:{index:"vimeo.com/",
id:"/",src:"https://player.vimeo.com/video/%id%?autoplay\x3d1"},gmaps:{index:"//maps.google.",src:"%id%\x26output\x3dembed"}}},proto:{initIframe:function(){a.types.push("iframe");g("BeforeChange",function(a,c,d){c!==d&&("iframe"===c?E():"iframe"===d&&E(!0))});g("Close.iframe",function(){E()})},getIframe:function(b,c){var d=b.src,f=a.st.iframe;e.each(f.patterns,function(){if(-1<d.indexOf(this.index))return this.id&&(d="string"==typeof this.id?d.substr(d.lastIndexOf(this.id)+this.id.length,d.length):
this.id.call(this,d)),d=this.src.replace("%id%",d),!1});var g={};return f.srcAction&&(g[f.srcAction]=d),a._parseMarkup(c,g,b),a.updateStatus("ready"),c}}});var F=function(b){var c=a.items.length;return b>c-1?b-c:0>b?c+b:b},J=function(a,c,d){return a.replace(/%curr%/gi,c+1).replace(/%total%/gi,d)};e.magnificPopup.registerModule("gallery",{options:{enabled:!1,arrowMarkup:'\x3cbutton title\x3d"%title%" type\x3d"button" class\x3d"mfp-arrow mfp-arrow-%dir%"\x3e\x3c/button\x3e',preload:[0,2],navigateByImgClick:!0,
arrows:!0,tPrev:"Previous (Left arrow key)",tNext:"Next (Right arrow key)",tCounter:"%curr% of %total%"},proto:{initGallery:function(){var b=a.st.gallery;if(a.direction=!0,!b||!b.enabled)return!1;n+=" mfp-gallery";g("Open.mfp-gallery",function(){b.navigateByImgClick&&a.wrap.on("click.mfp-gallery",".mfp-img",function(){if(1<a.items.length)return a.next(),!1});h.on("keydown.mfp-gallery",function(b){37===b.keyCode?a.prev():39===b.keyCode&&a.next()})});g("UpdateStatus.mfp-gallery",function(b,d){d.text&&
(d.text=J(d.text,a.currItem.index,a.items.length))});g("MarkupParse.mfp-gallery",function(c,d,e,g){c=a.items.length;e.counter=1<c?J(b.tCounter,g.index,c):""});g("BuildControls.mfp-gallery",function(){if(1<a.items.length&&b.arrows&&!a.arrowLeft){var c=b.arrowMarkup,d=a.arrowLeft=e(c.replace(/%title%/gi,b.tPrev).replace(/%dir%/gi,"left")).addClass("mfp-prevent-close");c=a.arrowRight=e(c.replace(/%title%/gi,b.tNext).replace(/%dir%/gi,"right")).addClass("mfp-prevent-close");d.click(function(){a.prev()});
c.click(function(){a.next()});a.container.append(d.add(c))}});g("Change.mfp-gallery",function(){a._preloadTimeout&&clearTimeout(a._preloadTimeout);a._preloadTimeout=setTimeout(function(){a.preloadNearbyImages();a._preloadTimeout=null},16)});g("Close.mfp-gallery",function(){h.off(".mfp-gallery");a.wrap.off("click.mfp-gallery");a.arrowRight=a.arrowLeft=null})},next:function(){a.direction=!0;a.index=F(a.index+1);a.updateItemHTML()},prev:function(){a.direction=!1;a.index=F(a.index-1);a.updateItemHTML()},
goTo:function(b){a.direction=b>=a.index;a.index=b;a.updateItemHTML()},preloadNearbyImages:function(){var b=a.st.gallery.preload;var c=Math.min(b[0],a.items.length),d=Math.min(b[1],a.items.length);for(b=1;b<=(a.direction?d:c);b++)a._preloadItem(a.index+b);for(b=1;b<=(a.direction?c:d);b++)a._preloadItem(a.index-b)},_preloadItem:function(b){if(b=F(b),!a.items[b].preloaded){var c=a.items[b];c.parsed||(c=a.parseEl(b));k("LazyLoad",c);"image"===c.type&&(c.img=e('\x3cimg class\x3d"mfp-img" /\x3e').on("load.mfploader",
function(){c.hasSize=!0}).on("error.mfploader",function(){c.hasSize=!0;c.loadError=!0;k("LazyLoadError",c)}).attr("src",c.src));c.preloaded=!0}}}});e.magnificPopup.registerModule("retina",{options:{replaceSrc:function(a){return a.src.replace(/\.\w+$/,function(a){return"@2x"+a})},ratio:1},proto:{initRetina:function(){if(1<window.devicePixelRatio){var b=a.st.retina,c=b.ratio;1<(c=isNaN(c)?c():c)&&(g("ImageHasSize.retina",function(a,b){b.img.css({"max-width":b.img[0].naturalWidth/c,width:"100%"})}),
g("ElementParse.retina",function(a,e){e.src=b.replaceSrc(e,c)}))}}}});B()});