var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,c){a instanceof String&&(a=String(a));for(var f=a.length,g=0;g<f;g++){var b=a[g];if(e.call(c,b,g,a))return{i:g,v:b}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,c){a!=Array.prototype&&a!=Object.prototype&&(a[e]=c.value)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(a,e,c,f){if(e){c=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var g=a[f];g in c||(c[g]={});c=c[g]}a=a[a.length-1];f=c[a];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");
!function(a){window.onpageshow=function(a){a.persisted&&window.location.reload()};a(window).on("load",function(){var b=a(".preloader");setTimeout(function(){b.find(".spinner").velocity({opacity:"0",translateY:"-40px"},{duration:400,complete:function(){b.find(".box-1").velocity({translateY:"-100%"},{duration:1E3,easing:[.7,0,.3,1]});b.find(".box-2").velocity({translateY:"-100%"},{duration:400,easing:[.7,0,.3,1]})}})},1E3);a(".typed-subtitle").length&&1<a(".h-subtitle p").length&&a(".typed-subtitle").each(function(){a(this).typed({stringsElement:a(this).prev(".typing-subtitle"),
loop:!0})});var d=location.hash,c=a(d);0==d.indexOf("#section-")&&c.length&&a("body, html").animate({scrollTop:a(d).offset().top-68},400)});var e=a(window).width(),c=a(window).height();if(783>e&&a(".section.started").css({height:c}),a(".started-carousel").length){var f=new Swiper(".started-carousel .swiper-container",{init:!1,loop:!1,spaceBetween:0,effect:"fade",slidesPerView:1,simulateTouch:!1,autoplay:{delay:6E3,disableOnInteraction:!1,waitForTransition:!1}});f.on("slideChange",function(){var b=
f.realIndex,d=f.slides.length;a(".started-carousel .swiper-slide").removeClass("first");a(".started-carousel .swiper-slide").each(function(d,c){b-1>=d?a(c).addClass("swiper-clip-active"):a(c).removeClass("swiper-clip-active")});a(".started-carousel .swiper-slide").each(function(b,c){a(c).css({"z-index":d-b})})});f.init()}a(".content-carousel").length&&a(".owl-carousel").each(function(){var b=a(this),d=b.data("slidesview"),c=b.data("slidesview_mobile");b.owlCarousel({margin:40,items:d,autoplay:!1,
autoplayTimeout:5E3,autoplayHoverPause:!0,loop:!1,rewind:!0,nav:!1,dots:!1,responsive:{0:{margin:40,items:c},720:{margin:40,items:d},1200:{margin:40,items:d}}});b.closest(".content-carousel").find(".next").click(function(){a(this).closest(".content-carousel").find(".owl-carousel").trigger("next.owl.carousel",[800])});b.closest(".content-carousel").find(".prev").click(function(){a(this).closest(".content-carousel").find(".owl-carousel").trigger("prev.owl.carousel",[800])})});a(".animated-button span").each(function(b){b=
a(this).text().split("");var d=a(this);d.empty();a.each(b,function(a,b){d.append("\x3cem\x3e"+b+"\x3c/em\x3e")})});a("header .top-menu").on("click","a",function(){var b=a(this).attr("href");if(0==b.indexOf("#section-"))a("body").hasClass("home")||(location.href="/"+b),a("body, html").animate({scrollTop:a(b).offset().top-115},400),a("header").hasClass("active")&&a(".menu-btn").trigger("click");else{var d=a(".preloader");d.find(".box-1").velocity({translateY:"0%"},{duration:400,easing:[.7,0,.3,1]});
d.find(".box-2").velocity({translateY:"0%"},{duration:1E3,easing:[.7,0,.3,1],complete:function(){location.href=b}})}return!1});a(".section").length&&a(".top-menu li a").length&&a(window).on("scroll",function(){var b=a(window).scrollTop();a(".top-menu ul li a").each(function(){if(0==a(this).attr("href").indexOf("#section-")){var d=a(this),c=a(d.attr("href"));c.length&&c.offset().top<=b+120&&(a(".top-menu ul li").removeClass("current-menu-item"),d.closest("li").addClass("current-menu-item"))}})});a(window).on("scroll",
function(){100<=a(this).scrollTop()&&1<a(".section").length&&(a(".header").addClass("fixed"),a(".mouse-btn").fadeOut());100>=a(this).scrollTop()&&1<a(".section").length&&(a(".header").removeClass("fixed"),a(".mouse-btn").fadeIn())});a("header").on("click",".menu-btn",function(){return a("header").hasClass("active")?(a("header").removeClass("active"),a(".footer .soc").fadeIn(),a("body").addClass("loaded"),a(".video-bg").length&&a("body").addClass("background-enabled")):(a("header").addClass("active"),
a(".footer .soc").hide(),a("body").removeClass("loaded"),a("body").removeClass("background-enabled")),!1});a(".section").on("click",".mouse-btn",function(){a("body, html").animate({scrollTop:c-150},800)});1<a(".section").length&&a(".mouse-btn").show();var g=a(".section.works .box-items");g.imagesLoaded(function(){g.isotope({itemSelector:".box-col"})});a(".filters").on("click",".btn-group",function(){var b=a(this).find("input").val();g.isotope({filter:b});a(".filters .btn-group label").removeClass("glitch-effect");
a(this).find("label").addClass("glitch-effect")});/\.(?:jpg|jpeg|gif|png)$/i.test(a(".gallery-item:first a").attr("href"))&&a(".gallery-item a").magnificPopup({gallery:{enabled:!0},type:"image",closeBtnInside:!1,mainClass:"mfp-fade"});a(".has-popup-media").magnificPopup({type:"inline",overflowY:"auto",closeBtnInside:!0,mainClass:"mfp-fade"});a(".has-popup-image").magnificPopup({type:"image",closeOnContentClick:!0,mainClass:"mfp-fade",image:{verticalFit:!0}});a(".has-popup-video").magnificPopup({disableOn:700,
type:"iframe",iframe:{patterns:{youtube_short:{index:"youtu.be/",id:"youtu.be/",src:"https://www.youtube.com/embed/%id%?autoplay\x3d1"}}},removalDelay:160,preloader:!1,fixedContentPos:!1,mainClass:"mfp-fade",callbacks:{markupParse:function(a,c,e){a.find("iframe").attr("allow","autoplay")}}});a(".has-popup-music").magnificPopup({disableOn:700,type:"iframe",removalDelay:160,preloader:!1,fixedContentPos:!1,mainClass:"mfp-fade"});a(".has-popup-gallery").on("click",function(){var b=a(this).attr("href");
return a(b).magnificPopup({delegate:"a",type:"image",closeOnContentClick:!1,mainClass:"mfp-fade",removalDelay:160,fixedContentPos:!1,gallery:{enabled:!0}}).magnificPopup("open"),!1});a(".jarallax-video").length&&a(".jarallax-video").each(function(){a(this).jarallax()});setTimeout(function(){var b=a(".skills.dotted .progress"),c=b.width();b.length&&(b.append('\x3cspan class\x3d"dg"\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3c/span\x3e'),
b.find(".percentage").append('\x3cspan class\x3d"da"\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3cspan\x3e\x3c/span\x3e\x3c/span\x3e'),b.find(".percentage .da").css({width:c}))},1E3);e=a(".skills.circles .progress");e.length&&e.append('\x3cdiv class\x3d"slice"\x3e\x3cdiv class\x3d"bar"\x3e\x3c/div\x3e\x3cdiv class\x3d"fill"\x3e\x3c/div\x3e\x3c/div\x3e');
a(window).resize(function(){var b=a(window).width(),c=a(window).height();783>b&&a(".section.started").css({height:c});b=a(".skills-list.dotted .progress");c=b.width();b.length&&b.find(".percentage .da").css({width:c+1})})}(jQuery);