var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(c,e,b){c instanceof String&&(c=String(c));for(var d=c.length,a=0;a<d;a++){var g=c[a];if(e.call(b,g,a,c))return{i:a,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,e,b){c!=Array.prototype&&c!=Object.prototype&&(c[e]=b.value)};
$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(c,e,b,d){if(e){b=$jscomp.global;c=c.split(".");for(d=0;d<c.length-1;d++){var a=c[d];a in b||(b[a]={});b=b[a]}c=c[c.length-1];d=b[c];e=e(d);e!=d&&null!=e&&$jscomp.defineProperty(b,c,{configurable:!0,writable:!0,value:e})}};
$jscomp.polyfill("Array.prototype.find",function(c){return c?c:function(c,b){return $jscomp.findInternal(this,c,b).v}},"es6","es3");
!function(c){var e=function(b,d){this.el=c(b);this.options=c.extend({},c.fn.typed.defaults,d);this.isInput=this.el.is("input");this.attr=this.options.attr;this.showCursor=!this.isInput&&this.options.showCursor;this.elContent=this.attr?this.el.attr(this.attr):this.el.text();this.contentType=this.options.contentType;this.typeSpeed=this.options.typeSpeed;this.startDelay=this.options.startDelay;this.backSpeed=this.options.backSpeed;this.backDelay=this.options.backDelay;this.stringsElement=this.options.stringsElement;
this.strings=this.options.strings;this.stopNum=this.arrayPos=this.strPos=0;this.loop=this.options.loop;this.loopCount=this.options.loopCount;this.curLoop=0;this.stop=!1;this.cursorChar=this.options.cursorChar;this.shuffle=this.options.shuffle;this.sequence=[];this.build()};e.prototype={constructor:e,init:function(){var b=this;b.timeout=setTimeout(function(){for(var d=0;d<b.strings.length;++d)b.sequence[d]=d;b.shuffle&&(b.sequence=b.shuffleArray(b.sequence));b.typewrite(b.strings[b.sequence[b.arrayPos]],
b.strPos)},b.startDelay)},build:function(){var b=this;if(!0===this.showCursor&&(this.cursor=c('\x3cspan class\x3d"typed-cursor"\x3e'+this.cursorChar+"\x3c/span\x3e"),this.el.after(this.cursor)),this.stringsElement){b.strings=[];this.stringsElement.hide();var d=this.stringsElement.find("p");c.each(d,function(a,d){b.strings.push(c(d).html())})}this.init()},typewrite:function(b,d){if(!0!==this.stop){var a=this;a.timeout=setTimeout(function(){var c=0,e=b.substr(d);if("^"===e.charAt(0)){var f=1;/^\^\d+/.test(e)&&
(f+=(e=/\d+/.exec(e)[0]).length,c=parseInt(e));b=b.substring(0,d)+b.substring(d+f)}if("html"===a.contentType&&(e=b.substr(d).charAt(0),"\x3c"===e||"\x26"===e)){f="";for(f="\x3c"===e?"\x3e":";";b.substr(d).charAt(0)!==f;)b.substr(d).charAt(0),d++;d++}a.timeout=setTimeout(function(){if(d===b.length){if(a.options.onStringTyped(a.arrayPos),a.arrayPos!==a.strings.length-1||(a.options.callback(),a.curLoop++,!1!==a.loop&&a.curLoop!==a.loopCount))a.timeout=setTimeout(function(){a.backspace(b,d)},a.backDelay)}else{0===
d&&a.options.preStringTyped(a.arrayPos);var c=b.substr(0,d+1);a.attr?a.el.attr(a.attr,c):a.isInput?a.el.val(c):"html"===a.contentType?a.el.html(c):a.el.text(c);d++;a.typewrite(b,d)}},c)},Math.round(70*Math.random())+this.typeSpeed)}},backspace:function(b,d){if(!0!==this.stop){var a=this;a.timeout=setTimeout(function(){if("html"===a.contentType&&"\x3e"===b.substr(d).charAt(0)){for(;"\x3c"!==b.substr(d).charAt(0);)b.substr(d).charAt(0),d--;d--}var c=b.substr(0,d);a.attr?a.el.attr(a.attr,c):a.isInput?
a.el.val(c):"html"===a.contentType?a.el.html(c):a.el.text(c);d>a.stopNum?(d--,a.backspace(b,d)):d<=a.stopNum&&(a.arrayPos++,a.arrayPos===a.strings.length?(a.arrayPos=0,a.shuffle&&(a.sequence=a.shuffleArray(a.sequence)),a.init()):a.typewrite(a.strings[a.sequence[a.arrayPos]],d))},Math.round(70*Math.random())+this.backSpeed)}},shuffleArray:function(b){var d,a=b.length;if(a)for(;--a;){var c=b[d=Math.floor(Math.random()*(a+1))];b[d]=b[a];b[a]=c}return b},reset:function(){clearInterval(this.timeout);var b=
this.el.attr("id");this.el.after('\x3cspan id\x3d"'+b+'"/\x3e');this.el.remove();void 0!==this.cursor&&this.cursor.remove();this.options.resetCallback()}};c.fn.typed=function(b){return this.each(function(){var d=c(this),a=d.data("typed"),g="object"==typeof b&&b;a||d.data("typed",a=new e(this,g));"string"==typeof b&&a[b]()})};c.fn.typed.defaults={strings:["These are the default values...","You know what you should do?","Use your own!","Have a great day!"],stringsElement:null,typeSpeed:0,startDelay:0,
backSpeed:0,shuffle:!1,backDelay:500,loop:!1,loopCount:!1,showCursor:!0,cursorChar:"|",attr:null,contentType:"html",callback:function(){},preStringTyped:function(){},onStringTyped:function(){},resetCallback:function(){}}}(window.jQuery);